apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: node:18-alpine
        image: public.ecr.aws/r6l4g9e5/jenkinspipeline
        ports:
        - containerPort: 80